// ─────────────────────────────────────────────────────────────────────────────
// posts.js — Articoli del blog per La Perla del Mare
// ─────────────────────────────────────────────────────────────────────────────

export const posts = [
  {
    id: "cosa-fare-cesenatico-weekend",
    titolo: "5 cose da fare a Cesenatico in un weekend",
    data: "2025-03-10",
    categoria: "Guida locale",
    sommario: "Cesenatico non e solo mare e spiaggia — e una citta ricca di storia, natura e ottimo cibo. Ecco 5 esperienze autentiche da non perdere durante il tuo soggiorno.",
    contenuto: [
      { tipo: "paragrafo", testo: "Cesenatico sorprende sempre chi la visita per la prima volta. Conosciuta soprattutto come meta balneare, nasconde tesori storici, naturalistici e gastronomici che la rendono una destinazione perfetta tutto l'anno." },
      { tipo: "titoletto", testo: "1. Il Porto Canale Leonardesco" },
      { tipo: "paragrafo", testo: "Il porto canale di Cesenatico fu progettato da Leonardo da Vinci nel 1502 su incarico di Cesare Borgia. Oggi e uno dei simboli della citta, con i tipici trabaccoli romagnoli ancorati lungo le rive. Passeggiare lungo il porto al tramonto e un'esperienza indimenticabile." },
      { tipo: "titoletto", testo: "2. Il Museo della Marineria" },
      { tipo: "paragrafo", testo: "Sul porto canale si trova il Museo della Marineria — uno dei musei navali piu belli d'Italia. Otto imbarcazioni storiche restaurate raccontano la storia della navigazione adriatica. Imperdibile anche con i bambini." },
      { tipo: "titoletto", testo: "3. Il Parco di Levante" },
      { tipo: "paragrafo", testo: "A soli 4 minuti a piedi da La Perla del Mare, il Parco di Levante offre 40 ettari di prato, pineta, pioppi e querce. Due laghetti con fauna selvatica, area dog-friendly e sentieri perfetti per una passeggiata mattutina." },
      { tipo: "titoletto", testo: "4. Pesce fresco al mercato" },
      { tipo: "paragrafo", testo: "Il mercato del pesce di Cesenatico e uno dei piu animati della Riviera. La mattina presto i pescherecci scaricano il pescato fresco — orate, branzini, seppie, scampi. I ristoranti del porto cucinano il pesce del giorno in modo semplice e straordinario." },
      { tipo: "titoletto", testo: "5. Giro in bicicletta sul lungomare" },
      { tipo: "paragrafo", testo: "Con le biciclette incluse nel garage di La Perla del Mare puoi percorrere il lungo lungomare di Cesenatico fino a Cervia o in direzione Rimini. La pista ciclabile costiera e tra le piu belle d'Italia — piatta, panoramica e sempre ventilata." },
    ],
    attivo: true,
  },
  {
    id: "riviera-romagnola-vacanze-famiglia",
    titolo: "La Riviera Romagnola con i bambini: la guida completa",
    data: "2025-03-18",
    categoria: "Famiglia",
    sommario: "Cesenatico e dintorni sono una delle destinazioni piu family-friendly d'Italia. Parchi, spiagge attrezzate, musei interattivi e cibo che piace a tutti. Ecco la nostra guida.",
    contenuto: [
      { tipo: "paragrafo", testo: "La Riviera Romagnola e da decenni la meta preferita delle famiglie italiane per le vacanze estive. E non e un caso — spiagge piatte e sicure, servizi eccellenti, parchi divertimento e una cucina che mette d'accordo grandi e piccini." },
      { tipo: "titoletto", testo: "Perche Cesenatico con i bambini" },
      { tipo: "paragrafo", testo: "Cesenatico e a misura di bambino come poche altre localita. Il mare e basso e sicuro, il lungomare e percorribile in bicicletta senza traffico, i parchi sono a portata di piedi. La Perla del Mare e l'alloggio ideale per le famiglie: ascensore, box privato, camere separate e cucina completa." },
      { tipo: "titoletto", testo: "Il Parco Kinderland" },
      { tipo: "paragrafo", testo: "A soli 2 minuti a piedi da La Perla del Mare, il Parco Kinderland e un paradiso per i piu piccoli. Giostre, scivoli, aree gioco e animazione — i bambini non vogliono piu andare via." },
      { tipo: "titoletto", testo: "Mirabilandia e Italia in Miniatura" },
      { tipo: "paragrafo", testo: "A 30-40 minuti da Cesenatico si trovano due dei parchi divertimento piu famosi d'Italia. Mirabilandia e il piu grande parco italiano, con montagne russe e attrazioni per tutte le eta. Italia in Miniatura a Rimini e un classico intramontabile." },
      { tipo: "titoletto", testo: "La spiaggia" },
      { tipo: "paragrafo", testo: "Le spiagge di Cesenatico sono attrezzatissime — ombrelloni, sdraio, docce, bar, animazione e servizi bagnino. Il mare e basso per molti metri, ideale per i piu piccoli. In bicicletta da La Perla del Mare ci si arriva in 5 minuti." },
    ],
    attivo: true,
  },
  {
    id: "cesenatico-fuori-stagione",
    titolo: "Cesenatico fuori stagione: perche visitarla in primavera o autunno",
    data: "2025-04-01",
    categoria: "Ispirazione",
    sommario: "Cesenatico non e solo estate. In primavera e autunno la Riviera si trasforma — meno folla, prezzi bassi, natura splendida e la stessa ottima cucina. Ecco perche vale la pena venirci.",
    contenuto: [
      { tipo: "paragrafo", testo: "La maggior parte dei turisti conosce Cesenatico solo d'estate. Ma chi viene in primavera o in autunno scopre una localita completamente diversa — piu autentica, piu silenziosa, e per certi versi ancora piu bella." },
      { tipo: "titoletto", testo: "Primavera: la stagione perfetta" },
      { tipo: "paragrafo", testo: "Da aprile a giugno Cesenatico offre temperature miti, spiagge quasi deserte e prezzi molto piu bassi rispetto all'estate. Il mare inizia a scaldarsi, il lungomare e piacevolissimo in bicicletta e i ristoranti sono aperti senza code." },
      { tipo: "titoletto", testo: "Autunno: colori e sapori" },
      { tipo: "paragrafo", testo: "Settembre e ottobre sono mesi straordinari sulla Riviera. L'acqua del mare e ancora calda, la folla si dirada ma tutti i servizi sono ancora aperti. E la stagione delle sagre romagnole — piadina, crescioni, vino novello." },
      { tipo: "titoletto", testo: "Smart working al mare" },
      { tipo: "paragrafo", testo: "La Perla del Mare e perfetta per i nomadi digitali e i remote workers. WiFi fibra veloce, scrivania dedicata, cucina completa per cucinare in autonomia e la spiaggia vuota a 400 metri. Lavorare con il suono del mare in sottofondo e un lusso che pochi si permettono." },
      { tipo: "titoletto", testo: "Gite nell'entroterra" },
      { tipo: "paragrafo", testo: "Fuori stagione e il momento ideale per esplorare l'entroterra romagnolo. Bertinoro, il Balcone della Romagna, e a 25 minuti. Cesena con la sua magnifica Biblioteca Malatestiana e a 15 minuti. San Marino a 35 minuti." },
    ],
    attivo: true,
  },
  {
    id: "giro-italia-cervia-2026",
    titolo: "Il Giro d'Italia parte da Cervia: vivi la tappa dalla Riviera",
    data: "2026-04-15",
    categoria: "Eventi",
    sommario: "Il 17 maggio 2026 Cervia ospita la partenza della 9a tappa del Giro d'Italia. A soli 15 minuti da La Perla del Mare, un evento da non perdere. Scarica i nostri poster in omaggio.",
    contenuto: [
      { tipo: "paragrafo", testo: "Il 17 maggio 2026 la Riviera Romagnola si tinge di rosa. Cervia ospita la partenza della nona tappa della 109a edizione del Giro d'Italia — 184 km di grande ciclismo con arrivo in salita al Corno alle Scale, sull'Appennino bolognese. Una tappa che si annuncia decisiva per la classifica generale." },
      { tipo: "titoletto", testo: "La tappa nel dettaglio" },
      { tipo: "paragrafo", testo: "La partenza ufficiale (km 0) sara da Piazza Andrea Costa, con il percorso cittadino che attraversera via Nazario Sauro, il Lungomare d'Annunzio, viale Roma e via Martiri Fantini prima di lasciare Cervia in direzione Appennino. Per Cervia si tratta della quinta presenza del Giro — un traguardo storico che la citta celebrera tingendosi di rosa, in concomitanza con la storica festa dello Sposalizio del Mare." },
      { tipo: "titoletto", testo: "La Perla del Mare: la base perfetta per l'evento" },
      { tipo: "paragrafo", testo: "Cervia dista appena 15 minuti da Cesenatico in auto o in bicicletta lungo il lungomare. Soggiornare a La Perla del Mare significa avere una base comoda, accessoriata e a due passi dal mare per vivere questo evento straordinario senza lo stress di trovare alloggio a Cervia — dove i prezzi schizzeranno alle stelle nei giorni intorno alla tappa." },
      { tipo: "paragrafo", testo: "Con le biciclette incluse nel garage puoi persino pedalare fino a Cervia lungo la pista ciclabile costiera e assistere al passaggio della carovana rosa in modo autentico, come fanno i veri appassionati di ciclismo." },
      { tipo: "titoletto", testo: "Scarica i nostri poster in omaggio" },
      { tipo: "paragrafo", testo: "Per celebrare questo evento abbiamo creato due poster dedicati alla tappa Cervia - Corno alle Scale. Sono completamente gratuiti e scaricabili liberamente." },
      {
        tipo: "download",
        label1: "Scarica Poster 1",
        src1: "/Cervia_1.png",
        label2: "Scarica Poster 2",
        src2: "/Cervia_2.png"
      },
      { tipo: "titoletto", testo: "Informazioni pratiche" },
      { tipo: "paragrafo", testo: "Data: domenica 17 maggio 2026. Partenza: Piazza Andrea Costa, Cervia (RA). Arrivo: Corno alle Scale (BO). Distanza: 184 km. Tappa: 9a della 109a edizione del Giro d'Italia." },
    ],
    attivo: true,
  },
];
